{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6ad864bf-b23d-42cc-a8ba-9f15622d23d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "app.py — Global FactCheck Network (Dark Theme)\n",
    "\n",
    "This Streamlit app allows users to verify news headlines or claims using\n",
    "the Google Fact Check Tools API. It presents results in a professional,\n",
    "news-portal-style interface.\n",
    "\"\"\"\n",
    "\n",
    "# ===============================\n",
    "# 🧩 Import required libraries\n",
    "# ===============================\n",
    "import streamlit as st\n",
    "import requests\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from bs4 import BeautifulSoup\n",
    "from ftfy import fix_text\n",
    "\n",
    "# ===============================\n",
    "# 🔑 API Key Configuration\n",
    "# ===============================\n",
    "# Tries to read from Streamlit Secrets; fallback is None\n",
    "API_KEY = st.secrets.get(\"GOOGLE_FACTCHECK_API_KEY\", None)\n",
    "\n",
    "# ===============================\n",
    "# 🧹 Helper Function: Clean text\n",
    "# ===============================\n",
    "def clean_text(text):\n",
    "    \"\"\"\n",
    "    Cleans and normalizes text strings:\n",
    "    - Fixes unicode issues using ftfy\n",
    "    - Removes extra whitespace\n",
    "    \"\"\"\n",
    "    if not text:\n",
    "        return \"\"\n",
    "    text = fix_text(text)\n",
    "    return \" \".join(text.split()).strip()\n",
    "\n",
    "# ===============================\n",
    "# 🔍 Function: Fetch Fact-Check Results\n",
    "# ===============================\n",
    "def get_fact_check_results(query):\n",
    "    \"\"\"\n",
    "    Calls the Google Fact Check Tools API to find\n",
    "    fact-checks related to the given query string.\n",
    "    Returns a list of dictionaries (publisher, title, rating, url).\n",
    "    \"\"\"\n",
    "    if not API_KEY:\n",
    "        st.error(\"⚠️ Missing API Key. Please set GOOGLE_FACTCHECK_API_KEY in Streamlit secrets.\")\n",
    "        return []\n",
    "\n",
    "    api_url = \"https://factchecktools.googleapis.com/v1alpha1/claims:search\"\n",
    "    params = {\"query\": query, \"key\": API_KEY}\n",
    "\n",
    "    try:\n",
    "        response = requests.get(api_url, params=params, timeout=15)\n",
    "        response.raise_for_status()\n",
    "        data = response.json()\n",
    "        claims = data.get(\"claims\", [])\n",
    "\n",
    "        results = []\n",
    "        for claim in claims:\n",
    "            for review in claim.get(\"claimReview\", []):\n",
    "                results.append({\n",
    "                    \"publisher\": review.get(\"publisher\", {}).get(\"name\", \"Unknown\"),\n",
    "                    \"title\": review.get(\"title\", \"No title available\"),\n",
    "                    \"rating\": review.get(\"textualRating\", \"No Rating\"),\n",
    "                    \"url\": review.get(\"url\", \"#\")\n",
    "                })\n",
    "        return results\n",
    "\n",
    "    except Exception as e:\n",
    "        st.error(f\"❌ Error fetching data: {e}\")\n",
    "        return []\n",
    "\n",
    "# ===============================\n",
    "# 🎨 Streamlit Page Setup\n",
    "# ===============================\n",
    "def configure_page():\n",
    "    \"\"\"Set up page settings and dark theme styling.\"\"\"\n",
    "    st.set_page_config(page_title=\"📰 Global FactCheck Network\", layout=\"wide\")\n",
    "\n",
    "    # Inject custom dark theme CSS for a news-portal look\n",
    "    st.markdown(\"\"\"\n",
    "    <style>\n",
    "        /* General app background */\n",
    "        .stApp {\n",
    "            background: linear-gradient(180deg, #05070a, #0b0f12);\n",
    "            color: #e9f4ff;\n",
    "            font-family: 'Segoe UI', sans-serif;\n",
    "        }\n",
    "\n",
    "        /* Top header banner */\n",
    "        .topbar {\n",
    "            background: linear-gradient(90deg, #071029, #3b0f34);\n",
    "            padding: 18px;\n",
    "            border-radius: 10px;\n",
    "            margin-bottom: 20px;\n",
    "            box-shadow: 0 10px 30px rgba(0,0,0,0.6);\n",
    "        }\n",
    "        .topbar h1 {\n",
    "            margin: 0;\n",
    "            font-size: 2.2rem;\n",
    "            color: #fff;\n",
    "        }\n",
    "        .topbar p {\n",
    "            margin-top: 5px;\n",
    "            color: #bcd7ef;\n",
    "            opacity: 0.9;\n",
    "        }\n",
    "\n",
    "        /* Section containers */\n",
    "        .panel {\n",
    "            background: rgba(255,255,255,0.03);\n",
    "            padding: 16px;\n",
    "            border-radius: 10px;\n",
    "            border: 1px solid rgba(255,255,255,0.05);\n",
    "            margin-bottom: 20px;\n",
    "        }\n",
    "\n",
    "        /* Result cards */\n",
    "        .card {\n",
    "            background: linear-gradient(180deg, rgba(255,255,255,0.03), rgba(255,255,255,0.01));\n",
    "            padding: 12px;\n",
    "            border-radius: 10px;\n",
    "            margin-bottom: 12px;\n",
    "            border: 1px solid rgba(255,255,255,0.05);\n",
    "        }\n",
    "\n",
    "        .small { color:#9fb1c6; font-size:0.85rem; }\n",
    "        .muted { color:#99aebf; }\n",
    "    </style>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# ===============================\n",
    "# 🧠 Main App Function\n",
    "# ===============================\n",
    "def app():\n",
    "    \"\"\"Main Streamlit application.\"\"\"\n",
    "    configure_page()\n",
    "\n",
    "    # --- Header ---\n",
    "    st.markdown(\"\"\"\n",
    "    <div class=\"topbar\">\n",
    "        <h1>AI vs. Fact — Global FactCheck Network</h1>\n",
    "        <p>Verify any headline or claim using trusted global fact-checking sources.</p>\n",
    "    </div>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "    # --- Tabs ---\n",
    "    tabs = st.tabs([\"🏠 Home\", \"🔍 Fact Check\"])\n",
    "\n",
    "    # -----------------------------\n",
    "    # 🏠 HOME TAB\n",
    "    # -----------------------------\n",
    "    with tabs[0]:\n",
    "        st.markdown('<div class=\"panel\">', unsafe_allow_html=True)\n",
    "        st.subheader(\"Welcome to the Global FactCheck Network\")\n",
    "        st.write(\"\"\"\n",
    "        This tool lets you:\n",
    "        - ✅ Search for claims verified by fact-checking organizations  \n",
    "        - 🌐 Fetch results directly from Google Fact Check Tools API  \n",
    "        - 📰 Explore trustworthy verification sources in a single portal  \n",
    "        \"\"\")\n",
    "        st.markdown('</div>', unsafe_allow_html=True)\n",
    "\n",
    "    # -----------------------------\n",
    "    # 🔍 FACT-CHECK TAB\n",
    "    # -----------------------------\n",
    "    with tabs[1]:\n",
    "        st.markdown('<div class=\"panel\">', unsafe_allow_html=True)\n",
    "        st.subheader(\"Search for a Claim or Headline\")\n",
    "\n",
    "        # Input area\n",
    "        query = st.text_input(\"Enter your claim or news headline:\")\n",
    "\n",
    "        if st.button(\"Check Facts\"):\n",
    "            if not query.strip():\n",
    "                st.warning(\"⚠️ Please enter a statement or headline to verify.\")\n",
    "            else:\n",
    "                with st.spinner(\"Fetching verified fact-checks...\"):\n",
    "                    results = get_fact_check_results(query)\n",
    "\n",
    "                # --- Display results ---\n",
    "                if not results:\n",
    "                    st.info(\"No verified fact-checks found for this claim.\")\n",
    "                else:\n",
    "                    st.success(f\"✅ Found {len(results)} fact-check(s):\")\n",
    "\n",
    "                    for item in results:\n",
    "                        st.markdown('<div class=\"card\">', unsafe_allow_html=True)\n",
    "                        st.markdown(f\"**Source:** <span class='small'>{item['publisher']}</span>\", unsafe_allow_html=True)\n",
    "                        st.markdown(f\"**Verdict:** <span class='muted'>{item['rating']}</span>\", unsafe_allow_html=True)\n",
    "                        st.markdown(f\"[Read Full Article]({item['url']})\")\n",
    "                        st.markdown('</div>', unsafe_allow_html=True)\n",
    "\n",
    "        st.markdown('</div>', unsafe_allow_html=True)\n",
    "\n",
    "# ===============================\n",
    "# 🚀 Run the App\n",
    "# ===============================\n",
    "if __name__ == \"__main__\":\n",
    "    app()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
