{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f78106b0-0a2c-41d3-abff-fa08b2da252f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import requests\n",
    "from urllib.parse import quote_plus\n",
    "\n",
    "# --- Preserve existing logic: allow hardcoded API key as before but prefer st.secrets if available ---\n",
    "DEFAULT_API_KEY = \"AIzaSyCkhaQdU4Mla2mHHrxh3czlse6oPxsfImM\"\n",
    "API_KEY = st.secrets.get(\"GOOGLE_FACTCHECK_API_KEY\", DEFAULT_API_KEY) if hasattr(st, \"secrets\") else DEFAULT_API_KEY\n",
    "\n",
    "st.set_page_config(page_title=\"Global FactCheck Network\", layout=\"wide\", initial_sidebar_state=\"collapsed\")\n",
    "\n",
    "# --- Dark theme CSS & news-style layout ---\n",
    "st.markdown(\n",
    "    \"\"\"\n",
    "    <style>\n",
    "    /* Page background */\n",
    "    .stApp {\n",
    "        background: linear-gradient(180deg, #0b1014 0%, #0e1419 100%);\n",
    "        color: #E6EEF3;\n",
    "    }\n",
    "    /* Header card */\n",
    "    .header {\n",
    "        background: linear-gradient(90deg, rgba(7,54,66,0.9), rgba(139,0,92,0.85));\n",
    "        padding: 28px;\n",
    "        border-radius: 10px;\n",
    "        box-shadow: 0 8px 30px rgba(0,0,0,0.6);\n",
    "        margin-bottom: 18px;\n",
    "    }\n",
    "    .header h1 { margin: 0; font-size: 2.4rem; color: #fff; }\n",
    "    .header p { margin: 4px 0 0 0; color: #d8eaf2; opacity: 0.9; }\n",
    "\n",
    "    /* Search area */\n",
    "    .search-container {\n",
    "        background: rgba(255,255,255,0.03);\n",
    "        padding: 18px;\n",
    "        border-radius: 8px;\n",
    "        margin-bottom: 16px;\n",
    "        border: 1px solid rgba(255,255,255,0.04);\n",
    "    }\n",
    "    .search-input > div > div > input {\n",
    "        background: rgba(255,255,255,0.02) !important;\n",
    "        color: #e6eef3 !important;\n",
    "        border: 1px solid rgba(255,255,255,0.06) !important;\n",
    "    }\n",
    "    .search-button > button {\n",
    "        background: linear-gradient(90deg,#ff416c,#3f51b5) !important;\n",
    "        color: white !important;\n",
    "        border: none !important;\n",
    "        box-shadow: 0 6px 18px rgba(63,81,181,0.25) !important;\n",
    "    }\n",
    "\n",
    "    /* Result cards */\n",
    "    .card {\n",
    "        background: linear-gradient(180deg, rgba(255,255,255,0.02), rgba(255,255,255,0.01));\n",
    "        padding: 14px;\n",
    "        border-radius: 10px;\n",
    "        margin-bottom: 12px;\n",
    "        border: 1px solid rgba(255,255,255,0.03);\n",
    "    }\n",
    "    .card .meta { color: #9fb1c6; font-size: 0.9rem; margin-bottom: 6px; }\n",
    "    .badge {\n",
    "        display:inline-block;\n",
    "        padding:6px 10px;\n",
    "        border-radius:20px;\n",
    "        font-weight:600;\n",
    "        font-size:0.85rem;\n",
    "        margin-left:8px;\n",
    "    }\n",
    "    .badge.TRUE { background: rgba(46,204,113,0.15); color: #2ee071; border: 1px solid rgba(46,204,113,0.25); }\n",
    "    .badge.FALSE { background: rgba(231,76,60,0.12); color: #ff6b6b; border: 1px solid rgba(231,76,60,0.18); }\n",
    "    .badge.NA { background: rgba(255,255,255,0.03); color: #d1dbe6; border: 1px solid rgba(255,255,255,0.03); }\n",
    "\n",
    "    a.link-button {\n",
    "        display:inline-block;\n",
    "        padding:8px 12px;\n",
    "        border-radius:8px;\n",
    "        background: rgba(255,255,255,0.02);\n",
    "        border: 1px solid rgba(255,255,255,0.04);\n",
    "        color: #dceefc;\n",
    "        text-decoration: none;\n",
    "        margin-top:6px;\n",
    "    }\n",
    "\n",
    "    </style>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True,\n",
    ")\n",
    "\n",
    "# Header\n",
    "st.markdown(\n",
    "    \"\"\"\n",
    "    <div class=\"header\">\n",
    "        <h1>Global FactCheck Network</h1>\n",
    "        <p>Professional verification search — news portal style. Enter a claim or headline and get verified fact-checks.</p>\n",
    "    </div>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True,\n",
    ")\n",
    "\n",
    "# Search container\n",
    "st.markdown('<div class=\"search-container\">', unsafe_allow_html=True)\n",
    "query = st.text_input(\"\", placeholder=\"Type a claim or headline to verify (e.g. “X country banned Y”)\", key=\"fact_query\")\n",
    "col1, col2, col3 = st.columns([6,1,1])\n",
    "with col2:\n",
    "    check_btn = st.button(\"Check\", key=\"check_btn\", help=\"Query Google Fact Check Tools API\")\n",
    "with col3:\n",
    "    clear_btn = st.button(\"Clear\", key=\"clear_btn\")\n",
    "st.markdown(\"</div>\", unsafe_allow_html=True)\n",
    "\n",
    "if clear_btn:\n",
    "    st.session_state[\"fact_query\"] = \"\"\n",
    "\n",
    "if check_btn:\n",
    "    if not query or not query.strip():\n",
    "        st.warning(\"Please enter a claim or headline to search.\")\n",
    "    else:\n",
    "        q = query.strip()\n",
    "        url = f\"https://factchecktools.googleapis.com/v1alpha1/claims:search?query={quote_plus(q)}&key={API_KEY}\"\n",
    "        with st.spinner(\"Searching verified fact-checks...\"):\n",
    "            try:\n",
    "                resp = requests.get(url, timeout=15)\n",
    "                data = resp.json()\n",
    "            except Exception as e:\n",
    "                st.error(f\"Request failed: {e}\")\n",
    "                data = {}\n",
    "\n",
    "        if \"claims\" in data and data[\"claims\"]:\n",
    "            st.success(f\"Found {len(data['claims'])} related claim(s).\")\n",
    "            for claim in data[\"claims\"]:\n",
    "                st.markdown('<div class=\"card\">', unsafe_allow_html=True)\n",
    "                text = claim.get(\"text\", \"—\")\n",
    "                # show headline\n",
    "                st.markdown(f\"### {text}\")\n",
    "                # show each review under claimReview\n",
    "                for review in claim.get(\"claimReview\", []):\n",
    "                    pub = review.get(\"publisher\", {}).get(\"name\", \"Unknown\")\n",
    "                    rating = review.get(\"textualRating\", None)\n",
    "                    rtitle = review.get(\"title\", review.get(\"url\", \"\")) or \"\"\n",
    "                    rurl = review.get(\"url\", \"#\")\n",
    "                    # rating badge class\n",
    "                    badge_class = \"NA\"\n",
    "                    if rating:\n",
    "                        low = rating.upper()\n",
    "                        if \"TRUE\" in low:\n",
    "                            badge_class = \"TRUE\"\n",
    "                        elif \"FALSE\" in low or \"PANTS\" in low or \"FLIP\" in low:\n",
    "                            badge_class = \"FALSE\"\n",
    "                        else:\n",
    "                            badge_class = \"NA\"\n",
    "                    st.markdown(f'<div class=\"meta\"><strong>{pub}</strong> <span class=\"badge {badge_class}\">{rating or \"No Rating\"}</span></div>', unsafe_allow_html=True)\n",
    "                    if rtitle:\n",
    "                        st.markdown(f\"**{rtitle}**\")\n",
    "                    st.markdown(f'<a class=\"link-button\" target=\"_blank\" href=\"{rurl}\">Read full article</a>', unsafe_allow_html=True)\n",
    "                    st.markdown(\"---\")\n",
    "                st.markdown(\"</div>\", unsafe_allow_html=True)\n",
    "        else:\n",
    "            st.info(\"No fact-checks found for this query.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
